# Generated by Django 3.2.12 on 2022-03-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
