# Generated by Django 3.2.12 on 2022-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=100, verbose_name='学部学科'),
        ),
    ]
