# Generated by Django 3.2.12 on 2022-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(default='img/django-img.svg', upload_to='images', verbose_name='イメージ画像'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank='True', default='img/django-thumbnail.svg', null='True', upload_to='images', verbose_name='サムネイル'),
        ),
    ]
